### ISSUE TITLE
 EUSB: Impossible to parse JSON

### ISSUE THREAD

**Issue by GitHubAIH** [guillaumezin/DomoticzEbusd#15]
Domoticz gives this error:

2024-07-10 22:22:00.359 Error: EUSB: Impossible to parse JSON (buffer size 327713). Traceback (most recent call last): File "/home/domo_user/domoticz/plugins/ebusd/plugin.py", line 342, in parseJson dJson = json.loads(sData, object_pairs_hook= lambda dict: CaseInsensitiveDict(dict)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/__init__.py", line 359, in loads return cls(**kw).decode(s) ^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/decoder.py", line 337, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode obj, end = self.scan_once(s, idx) ^^^^^^^^^^^^^^^^^^^^^^ json.decoder.JSONDecodeError: Invalid control character at: line 7154 column 19 (char 327595)

**Comment by guillaumezin** [comment]
Hello,
What do you see if you go to http://yourebusurl:httpportconfiguredinEBUSD_OPTS ? Can you post it?

**Comment by guillaumezin** [comment]
Ok, forget it, I have the same problem, probably related to ebusd version, I upgraded it a few days ago, I will dig a bit

**Comment by GitHubAIH** [comment]
It's indeed Ebusd bug:

![json error](https://github.com/guillaumezin/DomoticzEbusd/assets/170141463/bea583b0-eec3-4e74-aadf-a6e6b5a918c3)

**Comment by guillaumezin** [comment]
The bug is in ebusd:
https://github.com/john30/ebusd/issues/1304
Please add --updatecheck=off to EBUSD_OPTS or EBUSD_UPDATECHECK=off to your docker-compose.yml file as long as upstream bug is not fixed

**Comment by guillaumezin** [comment]
This is fixed upstream, should be ok in next version of ebusd.
