### ISSUE TITLE
Error: (EBusD) Impossible to parse JSON (buffer size 30122)

### ISSUE THREAD

**Issue by david-ge** [guillaumezin/DomoticzEbusd#8]
Hello,

I am facing similar issues like #7 :

```
2020-03-30 11:50:12.004 Error: (EBusD) Impossible to parse JSON (buffer size 30122). Traceback (most recent call last):
2020-03-30 11:50:12.004 File "/opt/domoticz/plugins/ebus/plugin.py", line 380, in parseJson
2020-03-30 11:50:12.004 dJson = json.loads(sData, object_pairs_hook= lambda dict: CaseInsensitiveDict(dict))
2020-03-30 11:50:12.004 File "/usr/lib/python3.7/json/__init__.py", line 361, in loads
2020-03-30 11:50:12.004 return cls(**kw).decode(s)
2020-03-30 11:50:12.004 File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
2020-03-30 11:50:12.004 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2020-03-30 11:50:12.004 File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
2020-03-30 11:50:12.004 obj, end = self.scan_once(s, idx)
2020-03-30 11:50:12.004 json.decoder.JSONDecodeError: Expecting ',' delimiter: line 181 column 86 (char 7888) 
```

ebusd version: 3.4.v3.4-14-gfb32960
Domoticz version: 2020.1
dzVents Version: 3.0.1
Python Version: 3.7.3 (default, Dec 20 2019, 18:57:59) [GCC 8.3.0]

Let me know, if you need the complete JSON or any other information.

Can you help me?

Regards,
David

**Comment by guillaumezin** [comment]
Hello,

Can you open http://ipofyourebusdevice:8889/data?def&write (8889 being the JSON HTTP port, change it if needed), put the result in a file and post the file as attachement here?

**Comment by david-ge** [comment]
Sure, please, check the attachment. But you are on a good way - Firefox gives me:

`SyntaxError: JSON.parse: expected ',' or '}' after property value in object at line 181 column 86 of the JSON data
`
So, the JSON is probably corrupted by ebusd.

[data.zip](https://github.com/guillaumezin/DomoticzEbusd/files/4402444/data.zip)

**Comment by david-ge** [comment]
Hello again,

thanks a lot for pushing me to the right direction. Problem found in one of the ebusd configuration CSVs. Corrected and working as expected.

Thank you!
